/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a document to an account-regional S3 bucket. */
        post: operations["upload_document"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a label with a MongoDB-generated ID. Duplicate names are allowed. */
        post: operations["create_label"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/labels/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a label. Document/trainer reference checks are not implemented. */
        delete: operations["delete_label"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read completed model metadata and evaluation. Resolve current label names through /labels. */
        get: operations["model_metadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trainers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate label IDs and store an untrained trainer in memory. Does not fit a model. */
        post: operations["create_trainer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trainers/{trainer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read trainer configuration, lifecycle state, error, or resulting model ID. */
        get: operations["trainer_metadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trainers/{trainer_id}/train": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Train and evaluate once, awaiting completion. Returns a new model ID. Disconnecting does not cancel training. */
        post: operations["train_model"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Supported model types. Add variants and their training dispatch together.
         * @enum {string}
         */
        ClassifierType: "nearest_centroid";
        CreateTrainerRequest: {
            classifier: components["schemas"]["ClassifierType"];
            documents: components["schemas"]["TrainingDocument"][];
            evaluation_strategy?: components["schemas"]["EvaluationStrategy"];
            /**
             * Format: int64
             * @description Random seed for reproducible splits. Generated and returned when omitted.
             */
            seed?: number | null;
            split?: components["schemas"]["SplitSettings"];
            tf_idf?: components["schemas"]["TfIdfSettings"];
        };
        ErrorResponse: {
            error: string;
        };
        EvaluationReport: {
            gap_summary: components["schemas"]["MetricSummary"];
            score_usage: string;
            /** Format: int64 */
            seed: number;
            selected_split: number;
            splits: components["schemas"]["SplitEvaluation"][];
            strategy: components["schemas"]["EvaluationStrategy"];
            test_summary: components["schemas"]["MetricSummary"];
            train_summary: components["schemas"]["MetricSummary"];
        };
        /** @enum {string} */
        EvaluationStrategy: "macro_f1" | "balanced_accuracy" | "matthews_correlation";
        /** @enum {string} */
        IdfWeightScheme: "base" | "smooth" | "maximum" | "probabilistic";
        LabelInput: {
            name: string;
        };
        LabelResponse: {
            id: string;
            name: string;
        };
        MetricSummary: {
            mean: components["schemas"]["Metrics"];
            /** @description Population standard deviation across the observed splits. */
            standard_deviation: components["schemas"]["Metrics"];
        };
        Metrics: {
            /** Format: double */
            balanced_accuracy: number;
            /** Format: double */
            macro_f1: number;
            /** Format: double */
            matthews_correlation: number;
        };
        ModelMetadata: {
            classifier: components["schemas"]["ClassifierType"];
            evaluation: components["schemas"]["EvaluationReport"];
            feature_count: number;
            label_ids: string[];
            /** Format: uuid */
            model_id: string;
            /** Format: int64 */
            seed: number;
            split: components["schemas"]["SplitSettings"];
            tf_idf: components["schemas"]["TfIdfSettings"];
            /** Format: uuid */
            trainer_id: string;
        };
        /** @enum {string} */
        SamplingStrategy: "random" | "stratified";
        SplitEvaluation: {
            gap: components["schemas"]["Metrics"];
            split_index: number;
            test: components["schemas"]["Metrics"];
            test_samples: number;
            train: components["schemas"]["Metrics"];
            train_samples: number;
        };
        SplitSettings: {
            /**
             * Format: float
             * @description Training fraction, strictly between zero and one.
             * @default 0.800000011920929
             */
            ratio: number;
            /**
             * @description Number of train/test splits; must be at least one.
             * @default 5
             */
            repetitions: number;
            /** @default stratified */
            sampling: components["schemas"]["SamplingStrategy"];
        };
        TfIdfSettings: {
            /**
             * Format: double
             * @default 0.5
             */
            double_normalization_k: number;
            /** @default base */
            idf_scheme: components["schemas"]["IdfWeightScheme"];
            /** @default raw_count */
            tf_scheme: components["schemas"]["TfWeightScheme"];
        };
        /** @enum {string} */
        TfWeightScheme: "binary" | "raw_count" | "normalization" | "double_normalization_half" | "double_normalization_variable";
        TrainerMetadata: {
            classifier: components["schemas"]["ClassifierType"];
            error?: string | null;
            evaluation_strategy: components["schemas"]["EvaluationStrategy"];
            label_ids: string[];
            /** Format: uuid */
            model_id?: string | null;
            /** Format: int64 */
            seed: number;
            split: components["schemas"]["SplitSettings"];
            status: components["schemas"]["TrainerStatus"];
            tf_idf: components["schemas"]["TfIdfSettings"];
            /** Format: uuid */
            trainer_id: string;
        };
        /** @enum {string} */
        TrainerStatus: "created" | "training" | "completed" | "failed";
        TrainingDocument: {
            /** @description Hexadecimal MongoDB label ID. Each class needs at least two documents. */
            label_id: string;
            name: string;
            pages: string[];
        };
        UploadDocumentRequest: {
            bucket_name?: string | null;
            /** Format: binary */
            file: string;
            metadata?: {
                [key: string]: string;
            } | null;
        };
        UploadDocumentResponse: {
            bucket_name: string;
            e_tag: string | null;
            object_key: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_document: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["UploadDocumentRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadDocumentResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_label: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabelInput"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_label: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabelResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    model_metadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelMetadata"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_trainer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTrainerRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainerMetadata"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    trainer_metadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trainer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainerMetadata"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    train_model: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trainer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelMetadata"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
